# Generated by Django 3.2.2 on 2021-05-07 13:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(help_text='Contains the resource type (e.g. Patient)', max_length=45)),
                ('resource_version', models.PositiveIntegerField(default=0, help_text='This is the current version ID of the resource', null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='Date that the first version of the resource was created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Date that the most recent version of the resource was created')),
                ('deleted_at', models.DateTimeField(help_text='If the most recent version of the resource is a delete, this contains the timestamp at which the resource was deleted. Otherwise, contains NULL', null=True)),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resources',
                'db_table': 'fhir_resource',
                'ordering': ['-published_at', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceVersion',
            fields=[
                ('persistent_id', models.AutoField(db_column='pid', help_text='The row persistent ID', primary_key=True, serialize=False)),
                ('resource_version', models.PositiveIntegerField(help_text='The specific version (starting with 1) of the resource that this row corresponds to')),
                ('resource_text', models.JSONField(help_text='The actual full text of the resource being stored')),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='Date that version was created version of the resource was created')),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rest_fhir.resource')),
            ],
            options={
                'verbose_name': 'resource',
                'verbose_name_plural': 'resource versions',
                'db_table': 'fhir_resource_ver',
                'ordering': ['resource', 'resource_version'],
                'unique_together': {('resource', 'resource_version')},
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_version_obj',
            field=models.ForeignObject(from_fields=['resource_id', 'resource_version'], null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rest_fhir.resourceversion', to_fields=['resource_id', 'resource_version']),
        ),
    ]
